// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmFuYQLD-uFN9VpxY6I0qQjrSTozuXK1Y',
    appId: '1:95359829503:web:303876623c6208a92fd3ca',
    messagingSenderId: '95359829503',
    projectId: 'rental-marina',
    authDomain: 'rental-marina.firebaseapp.com',
    storageBucket: 'rental-marina.appspot.com',
    measurementId: 'G-2NZLLFG2RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5V2PX9gxZEaBK0mMaT3oUe9NvN-6BOI',
    appId: '1:95359829503:android:358ea449614c9f7f2fd3ca',
    messagingSenderId: '95359829503',
    projectId: 'rental-marina',
    storageBucket: 'rental-marina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTdCgkdzfUqVLl_GFaWBbMjdt025ZgS0',
    appId: '1:95359829503:ios:928e6b587acd6f792fd3ca',
    messagingSenderId: '95359829503',
    projectId: 'rental-marina',
    storageBucket: 'rental-marina.appspot.com',
    iosBundleId: 'com.example.rentalMarina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClTdCgkdzfUqVLl_GFaWBbMjdt025ZgS0',
    appId: '1:95359829503:ios:928e6b587acd6f792fd3ca',
    messagingSenderId: '95359829503',
    projectId: 'rental-marina',
    storageBucket: 'rental-marina.appspot.com',
    iosBundleId: 'com.example.rentalMarina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmFuYQLD-uFN9VpxY6I0qQjrSTozuXK1Y',
    appId: '1:95359829503:web:6d93f668649a82c42fd3ca',
    messagingSenderId: '95359829503',
    projectId: 'rental-marina',
    authDomain: 'rental-marina.firebaseapp.com',
    storageBucket: 'rental-marina.appspot.com',
    measurementId: 'G-6K89QEB2NX',
  );

}